# Generated by Django 5.1.1 on 2024-11-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_grocerycategory_grocery_usergrocery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
