# Generated by Django 5.1.1 on 2024-11-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_grocery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='unit',
            field=models.CharField(choices=[('lb', 'Pound'), ('kg', 'Kilogram'), ('unit(s)', 'Unit(s)')], default='unit(s)', max_length=10),
        ),
    ]
