# Generated by Django 5.1.3 on 2024-11-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
