# Generated by Django 5.1.1 on 2024-11-21 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_grocery_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergrocery',
            name='grocery',
        ),
        migrations.AddField(
            model_name='usergrocery',
            name='grocery_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.grocerycategory'),
        ),
        migrations.AddField(
            model_name='usergrocery',
            name='grocery_name',
            field=models.CharField(default='Placeholder', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergrocery',
            name='unit',
            field=models.CharField(choices=[('lb', 'Pound'), ('kg', 'Kilogram'), ('unit(s)', 'Unit(s)')], default='unit(s)', max_length=10),
        ),
        migrations.AlterField(
            model_name='usergrocery',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Grocery',
        ),
    ]
