name: Docker Image CI

on:
  push:
    branches: [ "main","Femy_CI_CD_Branch", "Femy_Fresh" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

      # Save the Docker image to a tar file
    - name: Save Docker image to file
      run: docker save my-image-name:latest -o my-image-name.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: mealgenie-docker-image
        path: my-image-name.tar
